//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cls_DAL_FBB.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public articulo()
        {
            this.detalle = new HashSet<detalle>();
        }
    
        public int id_articulo { get; set; }
        public Nullable<System.DateTime> fecha_salida_inv { get; set; }
        public Nullable<System.DateTime> fecha_entrada_inv { get; set; }
        public decimal precio_sugerido { get; set; }
        public decimal precio_venta { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> cod_color { get; set; }
        public Nullable<int> cod_articulo { get; set; }
        public int cod_estado { get; set; }
    
        public virtual color color { get; set; }
        public virtual estado estado { get; set; }
        public virtual tipo_articulo tipo_articulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle> detalle { get; set; }
    }
}
