//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cls_DAL_FBB.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle
    {
        public int id_detalle { get; set; }
        public Nullable<int> cod_producto { get; set; }
        public Nullable<int> cod_venta { get; set; }
    
        public virtual articulo articulo { get; set; }
        public virtual venta venta { get; set; }
    }
}
