//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cls_DAL_FBB.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class donacion
    {
        public int id_donacion { get; set; }
        public System.DateTime fecha_donacion { get; set; }
        public decimal monto { get; set; }
        public string detalle { get; set; }
        public int cod_estado { get; set; }
    
        public virtual estado estado { get; set; }
    }
}
