//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cls_DAL_FBB.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int id_usuario { get; set; }
        public string email { get; set; }
        public string contrasena { get; set; }
        public Nullable<int> cod_rol { get; set; }
        public int cod_estado { get; set; }
    
        public virtual estado estado { get; set; }
        public virtual rol rol { get; set; }
    }
}
